global:
  name: pretrain-itervm
  phase: train
  stage: pretrain-vision
  workdir: workdir
  seed: ~
 
dataset:
  train: {
    roots: ['data_train/syn45k_train', 'data_train/100k','data_train/300k_vin_dict'],
    batch_size: 64
  }
  test: {
    roots: ['./data_train/syn45k_test'],
    batch_size: 64
  }
  data_aug: True
  multiscales: False
  num_workers: 4

  case_sensitive: True
  
training:
  epochs: 20
  show_iters: 500
  eval_iters: 8000
  save_iters: 8000

optimizer:
  type: Adam
  true_wd: False
  wd: 0.0
  bn_wd: False
  clip_grad: 20
  lr: 0.0001
  args: {
    betas: !!python/tuple [0.9, 0.999], # for default Adam 
  }
  scheduler: {
    periods: [8, 12],
    gamma: 0.1,
  }

model:
  name: 'modules.model_vision.BaseIterVision'
  checkpoint: ~
  vision: {
    loss_weight: 1.,
    attention: 'position',
    backbone: 'transformer',
    backbone_ln: 3,
    iter_size: 3,
    backbone_alpha_d: 0.5,
    checkpoint: ~
  }