global:
  name: pretrain-vm
  phase: train
  stage: pretrain-vision
  workdir: workdir
  seed: ~
 
dataset:
  train: {
    roots: ['../data/rec_train_data/lmdb/synaugment', '../data/rec_train_data/lmdb/syndata', '../data/rec_train_data/lmdb/ori'],
    batch_size: 256
  }
  test: {
    roots: ['../data/rec_train_data/lmdb/evaldata'],
    batch_size: 256
  }
  data_aug: True
  multiscales: False
  num_workers: 4
  case_sensitive: True
  
training:
  epochs: 40
  show_iters: 50
  eval_iters: 1000
  save_iters: 1000
  
optimizer:
  type: Adam
  true_wd: False
  wd: 0.0
  bn_wd: False
  clip_grad: 20
  lr:  0.0001
  args: {
    betas: !!python/tuple [0.9, 0.999], # for default Adam 
  }
  scheduler: {
    periods: [20, 20],
    gamma: 0.1,
  }

model:
  name: 'modules.model_vision.BaseVision'
   
  vision: {
    loss_weight: 1.,
    attention: 'position',
    backbone: 'transformer',
    backbone_ln: 3,
    backbone_alpha_d: 0.5,
   
  }
