global:
  name: pretrain-language-model
  phase: train
  stage: pretrain-language
  workdir: workdir
  seed: 42
 
dataset:
  train: {
    roots: ['./WikiText-train.csv'],
    batch_size: 2048
  }
  test: {
    roots: ['./WikiText-test.csv'],
    batch_size: 2048
  }
  num_workers: 4
  
training:
  epochs: 30
  show_iters: 200
  eval_iters: 5000
  save_iters: 5000

optimizer:
  type: Adam
  true_wd: False
  wd: 0.0
  bn_wd: False
  clip_grad: 20
  lr: 0.0001
  args: {
    betas: !!python/tuple [0.9, 0.999], # for default Adam 
  }
  scheduler: {
    periods: [25, 25],
    gamma: 0.1,
  }

model:
  name: 'modules.model_language.BCNLanguage'
  checkpoin: ~
  language: {
    num_layers: 4,
    loss_weight: 1.,
    use_self_attn: False
  }
